# Generated by Django 5.1.4 on 2024-12-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('figma_link', models.CharField(max_length=800)),
                ('mentor', models.CharField(max_length=200)),
                ('github_link', models.CharField(max_length=800)),
                ('hosted_url', models.CharField(default=None, max_length=800)),
                ('video_explanation', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='QueriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone.mentormodel')),
                ('std_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone.studentmodel')),
            ],
        ),
    ]
