# Generated by Django 5.1.4 on 2024-12-13 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='hosted_url',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='video_explanation',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='Mentor_Name',
            field=models.CharField(choices=[('Rishab Sir', 'Rishab Sir'), ('Vishal Sir', 'Vishal Sir'), ('Rahul Sir', 'Rahul Sir')], default='Rishab Sir', max_length=200),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='explanation_link',
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='hosted_link',
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentormodel',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mentormodel',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='figma_link',
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='github_link',
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1000)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone.mentormodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='QueriesModel',
        ),
    ]
