# Generated by Django 5.1.4 on 2024-12-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_remove_studentmodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=200)),
                ('mentor', models.CharField(max_length=200)),
                ('figma_link', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.EmailField(default=None, max_length=254)),
                ('hosted_link', models.CharField(default=None, max_length=800)),
                ('github_link', models.CharField(default=None, max_length=800)),
                ('explanation_link', models.CharField(default=None, max_length=800)),
            ],
        ),
        migrations.AddField(
            model_name='querymodel',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='mentormodel',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='querymodel',
            name='mentor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='querymodel',
            name='student',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
