# Generated by Django 5.1.4 on 2024-12-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_capstonemodel_resultmodel_submissionmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymodel',
            name='figma_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
