# Generated by Django 5.1.4 on 2024-12-15 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_querymodel_figma_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querymodel',
            name='figma_url',
        ),
    ]
