# Generated by Django 5.1.4 on 2024-12-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_remove_querymodel_figma_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='student',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
