# Generated by Django 5.1.4 on 2024-12-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_alter_submissionmodel_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorModel',
        ),
    ]
