# Generated by Django 5.1.4 on 2024-12-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_delete_mentormodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultModel',
        ),
    ]
