# Generated by Django 5.1.4 on 2024-12-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_delete_resultmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymodel',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
