# Generated by Django 5.1.4 on 2024-12-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('html_structure', models.IntegerField()),
                ('css_design', models.IntegerField()),
                ('responsiveness', models.IntegerField()),
                ('funtional_design', models.IntegerField()),
                ('debugging', models.IntegerField()),
            ],
        ),
    ]
