# Generated by Django 5.1.4 on 2024-12-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_marksmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marksmodel',
            old_name='funtional_design',
            new_name='functional_design',
        ),
    ]
